; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.9"

; Modules
projects[audiofield][subdir] = "sites/all/modules/contrib/audiofield"
projects[audiofield][version] = "1.0-beta3"

projects[ctools][subdir] = "sites/all/modules/contrib/ctools"
projects[ctools][version] = "1.0-rc1"

projects[views][subdir] = "sites/all/modules/contrib/views"
projects[views][version] = "3.0-rc3"

