; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.9"

; Modules
projects[audiofield][subdir] = "sites/all/modules/sites/all/modules/contrib/audiofield/audiofield"
projects[audiofield][version] = "1.0-beta3"

projects[ctools][subdir] = "sites/all/modules/sites/all/modules/contrib/ctools/ctools"
projects[ctools][version] = "1.0-rc1"

projects[views][subdir] = "sites/all/modules/sites/all/modules/contrib/views/views"
projects[views][version] = "3.0-rc3"

; Themes
projects[adaptivetheme][version] = "2.1"

projects[andromeda][version] = "2.x-dev"

projects[sky][version] = "2.2"

